#PARA UTILIZAR ESSES ENDPOINTS É NECESSÁRIO INSTALAR A EXTENSÃO DO VSCODE "REST CLIENT"
###

GET http://localhost:3333/livros

###

POST http://localhost:3333/livros
Content-Type: application/json

{
    "titulo": "Metamorphosis",
    "autor": "basedguy",
    "genero": "tragedia"
}

###

PUT http://localhost:3333/livros/2f2ae225-f179-4fca-bdfb-197c28183d34
Content-Type: application/json

{
    "titulo": "Senhor dos aneis",
    "autor": "J.K. Rolling",
    "genero": "Fantasy"
}

###

DELETE http://localhost:3333/livros/178f963e-1f48-423b-be7c-b6b8c7e2c335